//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mess_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyCost
    {
        public int MonthlyCostId { get; set; }
        public string Month_name { get; set; }
        public Nullable<float> total_cost { get; set; }
        public Nullable<float> avg_cost { get; set; }
        public Nullable<float> individual_cost { get; set; }
        public int managerId { get; set; }
    
        public virtual manager manager { get; set; }
    }
}
